---
permalink: rhel-install/task-uninstall-wfa-in-a-vcs-environment.html 
sidebar: sidebar 
keywords: uninstall, workflow, automation, vcs, environment 
summary: 'Puede desinstalar Workflow Automation (WFA) de un clúster eliminando todos los servicios de WFA de los nodos del clúster.' 
---
= Desinstalación de Workflow Automation en un entorno de VCS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede desinstalar Workflow Automation (WFA) de un clúster eliminando todos los servicios de WFA de los nodos del clúster.

.Pasos
. Desconecte los servicios mediante Cluster Manager:
+
.. Haga clic con el botón derecho en el grupo de clústeres.
.. Seleccione *sin conexión* y, a continuación, seleccione el nodo.


. Desinstale WFA en el primer nodo y, a continuación, desinstale WFA en el segundo nodo.
+
link:task-uninstall-oncommand-workflow-automation-linux.html["Desinstale OnCommand Workflow Automation"]

. Elimine los recursos del clúster de Cluster Manager:
+
.. Haga clic con el botón derecho en el grupo de clústeres.
.. Seleccione *Eliminar*.


. Elimine manualmente los datos de la ubicación compartida.

