---
permalink: rhel-install/task-reset-the-admin-password-created-during-installation-linux.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Si ha olvidado la contraseña del usuario administrador que creó al instalar el servidor OnCommand Workflow Automation (WFA), puede restablecerla.' 
---
= Restablece la contraseña de administrador creada durante la instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha olvidado la contraseña del usuario administrador que creó al instalar el servidor OnCommand Workflow Automation (WFA), puede restablecerla.

* Debe tener privilegios raíz para el sistema Linux en el que haya instalado WFA.
* Los servicios de WFA deben estar en ejecución.
* Este procedimiento restablece solo la contraseña del usuario administrador creada durante la instalación de WFA.
+
No puede restablecer la contraseña de otros usuarios administradores de WFA que haya creado después de la instalación de WFA.

* Este procedimiento no aplica la directiva de contraseñas que haya configurado.
+
Por lo tanto, debe introducir una contraseña que cumpla con su política de contraseña o cambiar la contraseña desde la interfaz de usuario de WFA después de haber restablecido la contraseña.



.Pasos
. Como usuario raíz, inicie sesión en el sistema Linux en el que está instalado WFA.
. En la confirmación del shell, desplácese hasta el siguiente directorio del servidor de WFA: WFA_install_location/wfa/bin/
. Introduzca el siguiente comando:
+
`./wfa --admin-password [--password=PASS]`

+
Si no ha proporcionado una contraseña, debe introducir la contraseña cuando se le solicite.

. En el indicador de comandos del shell, siga las instrucciones que aparecen en pantalla.

