---
permalink: rhel-install/task-modify-the-default-password-policy-linux.html 
sidebar: sidebar 
keywords: modify, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) está configurado para implementar una política de contraseñas para los usuarios locales. Puede modificar la política de contraseñas predeterminada.' 
---
= Modifique la política de contraseñas predeterminada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) está configurado para implementar una política de contraseñas para los usuarios locales. Puede modificar la política de contraseñas predeterminada.

Debe haber iniciado sesión en el sistema host de WFA como usuario raíz.

* La ruta de instalación predeterminada de WFA se utiliza en este procedimiento.
+
Si ha cambiado la ubicación predeterminada durante la instalación, debe utilizar la ruta de instalación de WFA cambiada.

* El comando para la directiva de contraseñas predeterminada es ./wfa --password-policy=default.
+
El valor predeterminado es "minLength=true,8;specialChar=true,1;digitalChar=true,1;lowercaChar=true,1;uppercaseChar=true,1;espaceChar=false" . Esto indica que la política de contraseña predeterminada debe tener una longitud mínima de ocho caracteres, debe contener al menos 1 carácter especial, 1 dígito, 1 carácter en minúscula, 1 carácter en mayúscula y sin espacios.



.Pasos
. En la confirmación del shell, desplácese hasta el siguiente directorio del servidor de WFA: WFA_install_location/wfa/bin/
. Modifique la política de contraseña predeterminada introduciendo el comando siguiente:
+
`./wfa --password-policy=PasswordPolicyString --restart=WFA`


