---
permalink: windows-install/reference-system-requirements-for-oncommand-workflow-automation-windows.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, system requirements, install 
summary: 'Debe estar al tanto de los requisitos de hardware y software de OnCommand Workflow Automation (WFA) antes de instalar WFA.' 
---
= Requisitos del sistema para instalar OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe estar al tanto de los requisitos de hardware y software de OnCommand Workflow Automation (WFA) antes de instalar WFA.



== Requisitos de hardware para instalar WFA

En la siguiente tabla se enumeran los requisitos mínimos de hardware y las especificaciones de hardware recomendadas para el servidor de WFA.

[cols="3*"]
|===
| Componente | Requisitos mínimos | Especificaciones recomendadas 


 a| 
CPU
 a| 
2.27 GHz o superior, 4 núcleos, 64 bits
 a| 
2.27 GHz o superior, 4 núcleos, 64 bits



 a| 
RAM
 a| 
4 GB
 a| 
8 GB



 a| 
Libere espacio en disco
 a| 
5 GB
 a| 
20 GB

|===
Si está instalando WFA en una máquina virtual (VM), debe reservar la memoria y la CPU necesarias para que la máquina virtual tenga suficientes recursos. El instalador no verifica la velocidad de la CPU.



== Requisitos de software para la instalación de WFA

WFA se ejecuta en un sistema operativo Windows de 64 bits y debe instalarse en máquinas físicas o máquinas virtuales dedicadas. No debe instalar ninguna otra aplicación en el servidor que ejecute WFA.

WFA se ejecuta desde Microsoft Windows Server 2012 Enterprise Edition hasta Microsoft Windows Server 2016 (todas las ediciones). Enterprise Edition es el sistema operativo Windows recomendado.

Para servidores Windows 2012, se debe instalar .NET Framework versión 4.5.2 en el sistema Windows. Si no está instalada la versión 4.5.2 de .NET Framework, se produce un error en la instalación de WFA 5.1.

* Uno de los siguientes exploradores compatibles:
+
** Mozilla Firefox
** Internet Explorer de Microsoft
** Google Chrome


* PowerShell 3.0
* VMware PowerCLI, versión 5
+

NOTE: La extensión PowerShell para las API de VMware solo es obligatoria si está utilizando WFA para ejecutar flujos de trabajo en VMware vSphere.




NOTE: Las aplicaciones antivirus pueden evitar que los servicios de WFA se inicien.

Para evitar este problema, configure las exclusiones del análisis antivirus para los siguientes directorios de WFA:

* El directorio en el que ha instalado WFA
* El directorio en el que ha instalado Perl
* El directorio en el que ha instalado OpenJDK
* El directorio de datos de MySQL


Para obtener más detalles, consulte la herramienta de matriz de interoperabilidad.

*Información relacionada*

https://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
