---
permalink: windows-install/task-reset-the-admin-password-created-during-installation.html 
sidebar: sidebar 
keywords: reset, admin password, created, installation 
summary: 'Si ha olvidado la contraseña del usuario administrador que creó durante la instalación del servidor OnCommand Workflow Automation (WFA), puede restablecer la contraseña.' 
---
= Restablece la contraseña de administrador creada durante la instalación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ha olvidado la contraseña del usuario administrador que creó durante la instalación del servidor OnCommand Workflow Automation (WFA), puede restablecer la contraseña.

* Debe tener privilegios de administrador para el sistema Windows en el que haya instalado WFA.
* Los servicios de WFA deben estar en ejecución.
* Este procedimiento solo restablece la contraseña del usuario administrador que se creó durante la instalación de WFA.
+
No puede restablecer la contraseña de otros usuarios administradores de WFA que haya creado después de la instalación de WFA.

* Este procedimiento no aplica la directiva de contraseñas que haya configurado.
+
Debe introducir una contraseña que cumpla con su política de contraseña o cambiar la contraseña desde la interfaz de usuario de WFA después de haber restablecido la contraseña.



.Pasos
. Abra un símbolo del sistema y desplácese al siguiente directorio: `WFA_install_location\WFA\bin\`
. Introduzca el siguiente comando:
+
`wfa --admin-password [--password=PASS]`

+
Si no ha introducido una contraseña en el comando, debe introducir la contraseña cuando se le solicite.

. En el símbolo del sistema, siga las instrucciones que aparecen en pantalla para restablecer la contraseña de administrador.

