---
permalink: windows-install/task-restore-regular-the-oncommand-workflow-automation-database-using-rest-apis.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, restore, regular, wfa, database, rest, apis 
summary: 'Puede realizar una restauración regular de la base de datos de OnCommand Workflow Automation (WFA) mediante las API DE REST. En una restauración normal, solo puede restaurar la base de datos de WFA.' 
---
= Restaure (regularmente) la base de datos de WFA utilizando las API DE REST
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar una restauración regular de la base de datos de OnCommand Workflow Automation (WFA) mediante las API DE REST. En una restauración normal, solo puede restaurar la base de datos de WFA.

* Debe haber creado un backup .zip de la base de datos de WFA.
* Debe tener credenciales de administrador o de arquitecto.
* Si va a restaurar la base de datos como parte del procedimiento de migración, debe realizar una restauración completa.


.Pasos
. Introduzca la siguiente URL en el explorador para cliente DE REST: `+https://IP address of WFA server/rest/backups+`
. En la ventana copia de seguridad, seleccione el método *POST*.
. En la lista desplegable *parte*, seleccione *cuerpo multiparte*.
. En el campo *Archivo*, introduzca la siguiente información:
+
.. En la lista desplegable *Tipo de contenido*, seleccione *multiparte/datos de formulario*.
.. En la lista desplegable *Charset*, seleccione *ISO-8859-1*.
.. En el campo **Nombre de archivo**, escriba el nombre del archivo de copia de seguridad como archivo de copia de seguridad.
.. Haga clic en *examinar*.
.. Seleccione la ubicación del archivo .zip backup.


. Desplácese hasta el directorio WFA_install_location\wfa\bin y reinicie los servicios de WFA:
. Compruebe que la operación de restauración se ha realizado correctamente y que se puede acceder a WFA.

