---
permalink: windows-install/task-migrate-oncommand-workflow-automation.html 
sidebar: sidebar 
keywords: migrate, oncommand, workflow, automation, installation 
summary: 'Puede migrar una instalación de OnCommand Workflow Automation (WFA) para mantener la clave de base de datos WFA única que se instala durante la instalación de WFA. Por ejemplo, puede migrar la instalación de WFA desde un servidor Windows 2012 a un servidor Windows 2016.' 
---
= Migre la instalación de OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede migrar una instalación de OnCommand Workflow Automation (WFA) para mantener la clave de base de datos WFA única que se instala durante la instalación de WFA. Por ejemplo, puede migrar la instalación de WFA desde un servidor Windows 2012 a un servidor Windows 2016.

* Debe realizar este procedimiento solo cuando desee migrar una instalación de WFA que incluya la clave de base de datos WFA a un servidor diferente.
* Una restauración de base de datos de WFA no migra la clave WFA.
* Al migrar una instalación de WFA no se migran los certificados SSL.
* La ruta de instalación predeterminada de WFA se utiliza en este procedimiento.
+
Si ha cambiado la ubicación predeterminada durante la instalación, debe utilizar la ruta de instalación de WFA cambiada.



.Pasos
. Acceda a la WFA mediante un navegador web como administrador.
. Realice un backup de la base de datos WFA.
. Abra un símbolo del sistema en el servidor de WFA y cambie los directorios a la siguiente ubicación: `c:\Program Files\NetApp\WFA\bin`
. Introduzca lo siguiente en el símbolo del sistema para obtener la clave de la base de datos:
+
`wfa.cmd -key`

. Observe la clave de la base de datos que se muestra.
. Desinstale WFA.
. Instale WFA en el sistema necesario.
. Abra el símbolo del sistema en el nuevo servidor WFA y cambie los directorios a la siguiente ubicación: `c:\Program Files\NetApp\WFA\bin`
. Introduzca lo siguiente en el símbolo del sistema para instalar la clave de base de datos:
+
`wfa.cmd -key=yourdatabasekey`

+
Subasedatosatkey es la clave que anotó de la instalación anterior de WFA.

. Restaure la base de datos de WFA desde el backup que ha creado.

