---
permalink: windows-install/task-disable-the-default-password-policy.html 
sidebar: sidebar 
keywords: disable, default, password policy 
summary: 'OnCommand Workflow Automation (WFA) está configurado para implementar una política de contraseñas para los usuarios locales. Si no desea usar la política de contraseñas, puede deshabilitarla.' 
---
= Desactive la directiva de contraseñas predeterminada
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) está configurado para implementar una política de contraseñas para los usuarios locales. Si no desea usar la política de contraseñas, puede deshabilitarla.

Debe haber iniciado sesión en el sistema host de WFA como administrador.

La ruta de instalación predeterminada de WFA se utiliza en este procedimiento. Si ha cambiado la ubicación predeterminada durante la instalación, debe utilizar la ruta de instalación de WFA cambiada.

.Pasos
. Abra el Explorador de Windows y vaya al siguiente directorio: `WFA_install_location\WFA\bin\.`
. Haga doble clic en el archivo ps.cmd.
+
Se abre un símbolo del sistema de la interfaz de línea de comandos (CLI) de PowerShell con los módulos ONTAP y WFA cargados en él.

. En el símbolo del sistema, introduzca lo siguiente:
+
`Set-WfaConfig -Name PasswordPolicy -Enable $false`

. Cuando se le solicite, reinicie los servicios de WFA.

