---
permalink: help/reference-edit-credentials-dialog-box.html 
sidebar: sidebar 
keywords: edit, credential, dialog box, enable, modify, exist 
summary: El cuadro de diálogo Editar credenciales le permite modificar una credencial existente. 
---
= Cuadro de diálogo Edit Credentials
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El cuadro de diálogo Editar credenciales le permite modificar una credencial existente.



== Parámetros de credenciales

* *Coincidencia*
+
Permite seleccionar el tipo de coincidencia de la credencial, que define la credencial de una dirección IP o nombre de host específicos, o de una subred o rango IP completos. Entre las opciones disponibles se incluyen las siguientes:

+
** Exact: Define una dirección IP o un nombre de host específicos
** Patrón: Define una subred o un intervalo IP completos


* *Tipo*
+
Permite seleccionar el tipo de credencial de la lista desplegable.

+
VMware vCenter no es compatible con Linux.

* *Nombre/IP*
+
Permite especificar el nombre de host o la dirección IP para la credencial.

* *Nombre de usuario*
+
Permite especificar el nombre de usuario para la credencial de.

* *Contraseña*
+
Permite especificar la contraseña para el nombre de usuario.

* *Sobrescribir valores predeterminados*
+
Permite sobrescribir los valores predeterminados del protocolo, el puerto y el tiempo de espera asociados con el tipo de sistema remoto seleccionado para la credencial.

+
La casilla de comprobación no está activada de forma predeterminada. Debe seleccionar la casilla de comprobación si desea sobrescribir los valores predeterminados.





== Tabla de protocolos

La tabla de protocolos muestra los números de puerto y los límites de tiempo de espera (en segundos) para los protocolos asociados con el sistema remoto seleccionado para la credencial.



== Botones de comando

* *Prueba*
+
Permite probar la conexión con el nombre de host o la dirección IP mediante el inicio de sesión con las credenciales requeridas.

* *Guardar*
+
Guarda los ajustes de configuración y cierra el cuadro de diálogo.

* *Cancelar*
+
Cancela los cambios, si los hay, y cierra el cuadro de diálogo.


