---
permalink: help/reference-new-approval-point-dialog-box.html 
sidebar: sidebar 
keywords: new, approval, point, dialog box, enable, add, point, checkpoint, workflow, pause, execution, resume 
summary: El cuadro de diálogo Nuevo punto de aprobación permite agregar un punto de aprobación como punto de control en un flujo de trabajo para pausar la ejecución del flujo de trabajo y reanudarlo según su aprobación. 
---
= Cuadro de diálogo Nuevo punto de aprobación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El cuadro de diálogo Nuevo punto de aprobación permite agregar un punto de aprobación como punto de control en un flujo de trabajo para pausar la ejecución del flujo de trabajo y reanudarlo según su aprobación.

* *Introducir comentario (opcional)*
+
Permite proporcionar información, como tiempo de cambio, usuario y comentarios, que permite ver cuándo y por qué se puso en pausa o se reanudó la ejecución del flujo de trabajo.

+
Los comentarios del punto de aprobación pueden incluir expresiones MVFLEX Expression Language (MVEL).

* *Introduzca la condición de ejecución (si la hay)*
+
Le permite especificar condiciones para la ejecución de un comando:

+
** Siempre
+
Ejecuta el comando incondicionalmente.

** Si se encuentra la siguiente variable
+
Permite ejecutar un comando solo cuando se encuentra la variable especificada. Puede especificar la variable en el cuadro.

** Si no se encuentra la siguiente variable
+
Le permite ejecutar un comando solo cuando no se encuentra la variable especificada. Puede especificar la variable en el cuadro.

** Si LA siguiente expresión ES VERDADERA
+
Permite ejecutar un comando sólo cuando la expresión MVEL especificada sea "'true'". Puede especificar la expresión en el cuadro.







== Botones de comando

* *OK*
+
Permite agregar el punto de aprobación.

* *Cancelar*
+
Cancela los cambios, si los hay, y cierra el cuadro de diálogo.


