---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: El cuadro de diálogo New Credentials permite crear una nueva credencial. 
---
= Cuadro de diálogo New Credentials
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
El cuadro de diálogo New Credentials permite crear una nueva credencial.



== Parámetros de credenciales

Puede configurar los siguientes parámetros para la credencial recién creada:

* *Coincidencia*
+
Permite seleccionar el tipo de coincidencia de la credencial, que define la credencial de una dirección IP o nombre de host específicos, o de una subred o rango IP completos. Es posible seleccionar una de las siguientes opciones:

+
** Exact: Define las credenciales de un nombre de host o IP específico
** Patrón: Define las credenciales para el rango de nombres de host o para toda la subred o rango de IP
+
Pattern es una expresión regular que se utiliza para hacer coincidir una cadena. Por ejemplo: `10.10.10.` Coincide con cualquier IP del intervalo comprendido entre 10.10.10.0 y 10.10.10.255, y. `host` coincide con todos los nombres de host que comienzan con `host`.



* *Tipo*
+
Permite seleccionar el tipo de host en la lista desplegable.

+

NOTE: VMware vCenter no es compatible con Linux.

* *Nombre/IP*
+
Permite especificar el nombre de host o la dirección IP para la credencial.

* *Nombre de usuario*
+
Permite especificar un nombre de usuario para la credencial.

* *Contraseña*
+
Permite especificar una contraseña para el nombre de usuario que se creó para la credencial de.

* *Sobrescribir valores predeterminados*
+
Permite sobrescribir los valores predeterminados del protocolo, el puerto y el tiempo de espera asociados con el tipo de sistema remoto seleccionado para la credencial.

+
La casilla de comprobación no está activada de forma predeterminada. Debe seleccionar la casilla de comprobación si desea sobrescribir los valores predeterminados.





== Botones de comando

* *Prueba*
+
Permite probar la conexión con el host o la dirección IP mediante el inicio de sesión con las credenciales requeridas.

* *Guardar*
+
Guarda los ajustes de configuración y cierra el cuadro de diálogo.

* *Cancelar*
+
Cancela los cambios, si los hay, y cierra el cuadro de diálogo.


