---
permalink: help/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: configure, oncommand, workflow, automation, use, microsoft, active, directory, lightweight, access, protocol, server, authentication, authorization 
summary: 'Puede configurar OnCommand Workflow Automation (WFA) para que utilice un servidor de protocolo ligero de acceso a directorios (LDAP) de Microsoft Active Directory (AD) para autenticación y autorización.' 
---
= Configure las opciones de autenticación
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar OnCommand Workflow Automation (WFA) para que utilice un servidor de protocolo ligero de acceso a directorios (LDAP) de Microsoft Active Directory (AD) para autenticación y autorización.

*Lo que necesitará*

Debe haber configurado un servidor LDAP de Microsoft AD en el entorno.

*Acerca de esta tarea*

Solo se admite la autenticación de Microsoft AD LDAP para WFA. No puede utilizar ningún otro método de autenticación LDAP, incluidos Microsoft AD Lightweight Directory Services (AD LDS) o el catálogo global de Microsoft.


NOTE: Durante la comunicación, LDAP envía el nombre de usuario y la contraseña en texto sin formato. Sin embargo, la comunicación LDAPS (LDAP Secure) es cifrada y segura.

.Pasos
. Inicie sesión en WFA a través de un navegador web como administrador.
. Haga clic en *Configuración* y en *Configuración* haga clic en *autenticación*.
. Active la casilla de verificación *Activar Active Directory*.
. Introduzca la información obligatoria en los campos:
+
.. *Opcional:* Si desea utilizar el formato _USER@Domain_ para usuarios de dominio, reemplace `sAMAccountName` con `userPrincipalName` En el campo *atributo de nombre de usuario*.
.. *Opcional:* Si se requieren valores únicos para su entorno, edite los campos necesarios.
.. Introduzca el URI del servidor AD de la siguiente forma: + ejemplo: `ldap://active_directory_server_address\[:port\]`
+
`ldap://NB-T01.example.com[:389]`

+
Si ha habilitado LDAP sobre SSL, puede usar el siguiente formato URI: `ldaps://active_directory_server_address\[:port\]`

.. Añadir una lista de nombres de grupos de AD con los roles requeridos.
+

NOTE: Puede agregar una lista de nombres de grupos de AD a los roles requeridos en la ventana grupos de Active Directory.



. Haga clic en *Guardar*.

