---
permalink: workflows/reference-guidelines-for-comments.html 
sidebar: sidebar 
keywords: aware, guidelines, powershell, perl, commnents, scripts, oncommand, workflow, automaion 
summary: 'Debe tener en cuenta las directrices para PowerShell y comentarios Perl en sus secuencias de comandos para OnCommand Workflow Automation (WFA).' 
---
= Directrices para comentarios
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Debe tener en cuenta las directrices para PowerShell y comentarios Perl en sus secuencias de comandos para OnCommand Workflow Automation (WFA).



== Comentarios sobre PowerShell

[cols="2*"]
|===
| Directrices | Ejemplo 


 a| 
Utilice el carácter # para un comentario de una sola línea.
 a| 
[listing]
----
# Single line comment
$options=$option.trim();
----


 a| 
Utilice el carácter # para un comentario de fin de línea.
 a| 
[listing]
----
$options=$option.trim(); # End of line
comment
----


 a| 
Utilice los caracteres <# y #> para un comentario de bloque.
 a| 
[listing]
----
<#
This is
a
block comment
#>
$options=$option.trim();
----
|===


== Comentarios Perl

[cols="2*"]
|===
| Directrices | Ejemplo 


 a| 
Utilice el carácter # para el comentario de una línea.
 a| 
[listing]
----
# convert from MBytes to Bytes
my $MaxDirectorySizeBytes = $MaxDirectorySize *
1024 * 1024;
----


 a| 
Utilice el carácter # para el comentario de fin de línea.
 a| 
[listing]
----
my $MaxDirectorySizeBytes = $MaxDirect
orySiZe * 1024 * 1024; # convert to Bytes
----


 a| 
Utilice el carácter # en cada línea con un # vacío al principio y al final para crear un borde de comentario para comentarios de varias líneas.
 a| 
[listing]
----
#
# This is a multi-line comment. Perl 5, unlike
# Powershell, does not have direct support for
# multi-line comments. Please use a '#'in every line
# with an empty '#' at the beginning and end to create
# a comment border
#
----


 a| 
No incluya código inactivo y comentado en los comandos de WFA. Sin embargo, para realizar pruebas, puede utilizar el mecanismo de documentación antigua simple (POD) para comentar el código.
 a| 
[listing]
----
=begin comment
	# Set deduplication
	if(defined $Deduplication && $Deduplication eq "enabled")
	{
		$wfaUtil->sendLog("Enabling Deduplication");
	}
=end comment
=cut
----
|===