---
permalink: workflows/task-check-in-an-already-existing-pack-into-scm.html 
sidebar: sidebar 
keywords: check, existing, packs, source, control, management, scm server, oncommand, workflow, automation 
summary: 'Puede realizar el check-in de paquetes ya existentes en el servidor de gestión de control de origen (SCM) desde OnCommand Workflow Automation (WFA).' 
---
= Compruebe los paquetes de flujo de trabajo de WFA existentes en el servidor SCM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar el check-in de paquetes ya existentes en el servidor de gestión de control de origen (SCM) desde OnCommand Workflow Automation (WFA).

.Lo que necesitará
El SCM debe estar configurado y debe tener credenciales de administrador o de arquitecto.

.Pasos
. Inicie sesión en la ventana *WFA* a través de un navegador web.
. Haga clic en *Administración de contenido* > *Paquetes*.
. Haga clic en el icono *Exportar al servidor*.
. En el cuadro de diálogo *Exportar a carpeta del servidor*, en el campo *ubicación de carpeta en el sistema del servidor*, introduzca la ubicación de la carpeta del servidor donde se guarda el paquete en el servidor.
+
De esta forma, exporta el paquete en forma explosionada en el sistema de archivos donde se crea el cliente SCM.

. En la ubicación del cliente SCM, compruebe el contenido del paquete en el servidor SCM.
. Utilice las herramientas Diff proporcionadas por SCM para verificar los cambios con respecto a la versión SCM del paquete.

